name: CodeQL Analysis for Web Files

on:
  push:
    branches: [ "feature/code-quality" ]

jobs:
  analyze:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # 1. 檢出程式碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 初始化 CodeQL，指定 JavaScript (涵蓋 JS、HTML、CSS)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-extended

      # 3. 建置資料庫（如果需要編譯，請在這裡加入 build 指令）
      - name: Build CodeQL database
        run: |
          echo "No build step required for HTML/CSS/JS"

      # 4. 執行分析，輸出 SARIF
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results.sarif

      # 5. 上傳 SARIF 檔案，方便下載或用 VS Code 檢視
      - name: Upload SARIF report
        uses: actions/upload-artifact@v3
        with:
          name: codeql-sarif-report
          path: results.sarif
